### ISSUE TITLE
ncurses build fails with odd error

### ISSUE THREAD

**Issue by taobrienlbl** [LBL-EESA/TECA_superbuild#32]
When compiling TECA_superbuild on an ubuntu 17.04 system w/ gcc 6.3.0, the build of `ncurses` fails as follows:

```bash
> /usr/bin/gcc-6 -DHAVE_CONFIG_H -I. -I/projects/teca-dev/TECA_superbuild/build/ncurses-6.0/ncurses -I../include -I/projects/teca-dev/TECA_superbuild/build/ncurses-6.0/ncurses/../include  -I/projects/teca-dev/local/include -D_GNU_SOURCE -DNDEBUG -I/projects/teca-dev/local/include  -O3 -march=native -mtune=native -DNDEBUG  --param max-inline-insns-single=1200 -c ../ncurses/lib_gen.c -o ../objects/lib_gen.o

In file included from ./curses.priv.h:325:0,
                 from ../ncurses/lib_gen.c:19:
_16582.c:843:15: error: expected ‘)’ before ‘int’
../include/curses.h:1631:56: note: in definition of macro ‘mouse_trafo’
 #define mouse_trafo(y,x,to_screen) wmouse_trafo(stdscr,y,x,to_screen)
                                                        ^
make[4]: *** [../objects/lib_gen.o] Error 1
make[3]: *** [all] Error 2
```
The cause of this error is unclear.

**Comment by CDCrystal** [comment]
I've met this issue this week. There're a simple solution to complie it with "CPPFLAGS=-P". I edited the CMakelists.txt and it worked.

**Comment by burlen** [comment]
I believe this has been resolved by upgrades to ncurse, we are building 6.1 now. If it remains an issue we can add an option to disable ncurses from the build, in favor of a system version, or add the flags mentioned above
